from .analysis import (
    BONUS_AFTER_DEDUCTION,
    EQUITY_AFTER_DEDUCTION,
    OTHER,
    REMAINING,
    SALARY_AFTER_DEDUCTION,
)
from .base import *

COLORS: dict[Category, str] = {
    # Income
    INCOME: "xkcd:sea blue",
    EARNED_INCOME: "xkcd:sea blue",
    SALARY: "xkcd:sea blue",
    SALARY_AFTER_DEDUCTION: "xkcd:sea blue",
    NON_TAXABLE_SALARY: "xkcd:sea blue",
    NON_TAXABLE_SALARY_HOUSING_BENEFIT: "xkcd:sea blue",
    CASH_BACK: "xkcd:sea blue",
    BONUS: "xkcd:gold",
    BONUS_AFTER_DEDUCTION: "xkcd:gold",
    EQUITY_VESTING: "xkcd:gold",
    EQUITY_AFTER_DEDUCTION: "xkcd:gold",
    BANK_INTEREST: "xkcd:gold",
    CAPITAL_GAIN: "xkcd:gold",
    REFUND_REIMBURSEMENT: "xkcd:lime",
    # Expense
    RENT: "xkcd:pinkish orange",
    SOCIAL_SECURITY: "xkcd:tree green",
    HEALTH_INSURANCE: "xkcd:tree green",
    HEALTH_INSURANCE_SALARY: "xkcd:tree green",
    HEALTH_INSURANCE_BONUS: "xkcd:tree green",
    WELFARE: "xkcd:indigo",
    WELFARE_SALARY: "xkcd:indigo",
    WELFARE_BONUS: "xkcd:indigo",
    UNEMPL_INS: "xkcd:indigo",
    UNEMPL_INS_SALARY: "xkcd:indigo",
    UNEMPL_INS_BONUS: "xkcd:indigo",
    MISC_INCOME_DEDUCTION: "xkcd:indigo",
    MISC_INCOME_DEDUCTION_SALARY: "xkcd:indigo",
    MISC_INCOME_DEDUCTION_BONUS: "xkcd:indigo",
    # ---
    TAX: "xkcd:purplish brown",
    CHARGED_TAX: "xkcd:purplish brown",
    NATIONAL_TAX_WITHHOLDING: "xkcd:purplish brown",
    NATIONAL_TAX_WITHHOLDING_SALARY: "xkcd:purplish brown",
    NATIONAL_TAX_WITHHOLDING_BONUS: "xkcd:purplish brown",
    NATIONAL_TAX_PAYMENT: "xkcd:purplish brown",
    NATIONAL_TAX_PREPAYMENT: "xkcd:purplish brown",
    NATIONAL_TAX_REPROJECTED: "xkcd:purplish brown",
    NATIONAL_TAX_REPROJECTED_EQUITY: "xkcd:purplish brown",
    LOCAL_TAX_DEDUCTION: "xkcd:purplish brown",
    LOCAL_TAX_PAYMENT: "xkcd:purplish brown",
    LOCAL_TAX_REPROJECTED: "xkcd:purplish brown",
    LOCAL_TAX_REPROJECTED_SALARY: "xkcd:purplish brown",
    LOCAL_TAX_REPROJECTED_BONUS: "xkcd:purplish brown",
    LOCAL_TAX_REPROJECTED_EQUITY: "xkcd:purplish brown",
    FURUSATO_DONATION: "xkcd:purplish brown",
    # ---
    ESTIMATED_UNPAID_TAX: "xkcd:light grey",
    ESTIMATED_UNPAID_TAX_SALARY: "xkcd:light grey",
    ESTIMATED_UNPAID_TAX_BONUS: "xkcd:light grey",
    ESTIMATED_UNPAID_TAX_EQUITY: "xkcd:light grey",
    # ---
    SAVED_TAX: "xkcd:light brown",
    SAVED_TAX_FROM_DEPENDENT_TRANSFER: "xkcd:light brown",
    SAVED_TAX_FROM_FURUSATO_DONATION: "xkcd:light brown",
    SAVED_TAX_FROM_RENT: "xkcd:light brown",
    # ---
    EXPENSE: "xkcd:salmon pink",
    SHOPPING: "xkcd:pinky purple",
    DAILY_SHOPPING: "xkcd:dark blue",
    MAJOR_SHOPPING: "xkcd:royal blue",
    UTILITY_BILL: "xkcd:teal",
    HOME_INSURANCE: "xkcd:light orange",
    CASH_OUT: "xkcd:faded green",
    DAILY_PUBLIC_TRANSPORT: "xkcd:mint green",
    ENTERTAINMENT: "xkcd:coral",
    TAXI: "xkcd:bright yellow",
    EDUCATION: "xkcd:slate",
    TRAVEL: "xkcd:light blue grey",
    MEDICAL: "xkcd:tree green",
    FOOD_DRINK_OUTSIDE: "xkcd:aqua blue",
    DIGITAL_SERVICE: "xkcd:bright blue",
    DEPENDENT_TRANSFER: "xkcd:spring green",
    # Misc
    OTHER: "xkcd:grey",
    REMAINING: "xkcd:gold",
}

XKCD_TO_HEX = {
    "xkcd:salmon pink": "#fe7b7c",
    "xkcd:pinkish orange": "#ff724c",
    "xkcd:pinky purple": "#c94cbe",
    "xkcd:dark blue": "#00035b",
    "xkcd:royal blue": "#0504aa",
    "xkcd:faded green": "#7bb274",
    "xkcd:sea blue": "#047495",
    "xkcd:slate": "#516572",
    "xkcd:grey": "#929591",
    "xkcd:gold": "#dbb40c",
    "xkcd:teal": "#029386",
    "xkcd:light orange": "#fdaa48",
    "xkcd:lime": "#aaff32",
    "xkcd:tree green": "#2a7e19",
    "xkcd:aqua blue": "#02d8e9",
    "xkcd:light blue grey": "#b7c9e2",
    "xkcd:light grey": "#d8dcd6",
    "xkcd:purplish brown": "#6b4247",
    "xkcd:indigo": "#380282",
    "xkcd:mint green": "#8fff9f",
    "xkcd:coral": "#fc5a50",
    "xkcd:bright yellow": "#fffd01",
    "xkcd:bright blue": "#0165fc",
    "xkcd:light brown": "#ad8150",
    "xkcd:spring green": "#a9f971",
}